config/routes.rb
Rails.application.routes.draw do
  root to: "api/users#root"

  namespace :api do
    resources :users
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id          :integer          not null, primary key
#  username    :string(255)
#  fname       :string(255)
#  description :text
#  uupc        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class User < ActiveRecord::Base

	has_attached_file :avatar, :styles => { 
		:large => '500x500', 
		:medium => "300x300>", 
		:small => "150x150>" }, :default_url => 'https://s3.amazonaws.com/gorendezvous/missing.GIF'

	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	def avatar_url_large
		avatar.url(:large)
	end

	def avatar_url_medium
		avatar.url(:medium)
	end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

	def root
	end

	def index
		@users = User.all
		render :json => @users.to_json(:methods => [:avatar_url_large, :avatar_url_medium])
	end

	def show
		@user = User.find(params[:id])
		render :json => @user.to_json(:methods => [:avatar_url_large, :avatar_url_medium])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			render :json => @user
		else
			render :json => {
				message: 'User Creation Failed',
				errors: @user.errors.full_messages
			}, status: 422
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			render :json => @user
		else
			render :json => {
				message: 'User Update Failed',
				errors: @user.errors.full_messages
			}, status: 422
		end
	end

	private

	def user_params
		# params.require(:user).permit(:avatar, :username, :fname, :uupc, :description)
		{
			avatar: params[:avatar],
			username: params[:username],
			fname: params[:fname],
			uupc: params[:uupc],
			description: params[:description]
		}
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rendezvous</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://cdn.pubnub.com/pubnub.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>All the Users</h1>

<% @users.each do |user| %>
	<%= user.fname %>
	<%= link_to "Check out this user!", user_url(user) %>
<% end %>

app/views/users/show.html.erb
<h1>A User</h1>

<%= user.fname %>
<%= user.description %>